before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  - id: default
    formats:
      - apk
      - deb
      - rpm
    contents:
      - src: package/config.yaml
        dst: /etc/solar-controller/config.yaml
        type: config
      - src: package/solar-controller.service
        dst: /etc/systemd/system/solar-controller.service
    scripts:
      postinstall: "package/postinstall.sh"
      postremove: "package/postremove.sh"
